Update Jenkinsfile3

diff --git a/Jenkinsfile3 b/Jenkinsfile3
--- a/Jenkinsfile3
+++ b/Jenkinsfile3
@@ -58,11 +58,11 @@ pipeline {
                                                 execCommand: """
                                                     cd /opt/docker/${svc}
                                                     npm install
-                                                    npm install eslint
-                                                    npm run lint || echo "Lint script not found, skipping lint"
+                                                 //   npm install eslint
+                                                //    npm run lint || echo "Lint script not found, skipping lint"
                                                     echo 'sonar.projectKey=${svc}' > sonar-scanner.properties
                                                     echo 'sonar.sources=.' >> sonar-scanner.properties
-                                                    echo 'sonar.host.url=https://sonarcloud.io' >> sonar-scanner.properties
+                                                    echo 'sonar.host.url=http://3.109.5.158:9000' >> sonar-scanner.properties
                                                     echo 'sonar.login=${SONAR_TOKEN}' >> sonar-scanner.properties
                                                     sonar-scanner -Dsonar.projectKey=${svc} -Dsonar.login=${SONAR_TOKEN} -Dproject.settings=sonar-scanner.properties
                                                 """,
